import torch
import os
folder_path = '/home/jz08/zhouzy/debug_pretrain/checkpoint-1/global_step1'
model = torch.load(os.path.join(folder_path,'mp_rank_00_model_states.pt'))
print(model.keys())
print(len(model))
# dict_keys(['module', 'lr_scheduler', 'data_sampler', 'random_ltd', 'sparse_tensor_module_names', 'skipped_steps', 'global_steps', 'global_samples', 'dp_world_size', 'mp_world_size', 'num_experts'])
# 11
buffer_names=[]
optimizer=None
shared_params={}
ds_config={
'fp16': {'enabled': False,
  'loss_scale': 0,
  'loss_scale_window': 1000,
  'initial_scale_power': 16,
  'hysteresis': 2,
  'min_loss_scale': 1},
 'bf16': {'enabled': True},
 'train_micro_batch_size_per_gpu': 4,
 'train_batch_size': 8,
 'gradient_accumulation_steps': 1,
 'zero_optimization': {'stage': 2,
  'overlap_comm': True,
  'contiguous_gradients': True,
  'sub_group_size': 1000000000.0,
  'reduce_bucket_size': 2359296},
 'timeout': 600,
 'steps_per_print': inf,
 'zero_allow_untested_optimizer': True
}
ds_version='0.9.5'
# dict_keys(['module', 'buffer_names', 'optimizer', 'param_shapes', 'frozen_param_shapes', 'shared_params', 'frozen_param_fragments', 'lr_scheduler', 'data_sampler', 'random_ltd', 'sparse_tensor_module_names', 'skipped_steps', 'global_steps', 'global_samples', 'dp_world_size', 'mp_world_size', 'ds_config', 'ds_version'])
# 18
"""
'param_shapes',
 'frozen_param_shapes', 'frozen_param_fragments',
[OrderedDict([('base_model.model.visual.blocks.0.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.0.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.0.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.0.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.0.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.0.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.0.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.0.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.1.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.1.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.1.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.1.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.1.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.1.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.1.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.1.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.2.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.2.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.2.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.2.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.2.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.2.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.2.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.2.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.3.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.3.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.3.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.3.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.3.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.3.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.3.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.3.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.4.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.4.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.4.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.4.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.4.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.4.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.4.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.4.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.5.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.5.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.5.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.5.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.5.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.5.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.5.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.5.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.6.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.6.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.6.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.6.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.6.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.6.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.6.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.6.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.7.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.7.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.7.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.7.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.7.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.7.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.7.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.7.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.8.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.8.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.8.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.8.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.8.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.8.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.8.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.8.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.9.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.9.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.9.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.9.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.9.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.9.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.9.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.9.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.10.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.10.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.10.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.10.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.10.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.10.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.10.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.10.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.11.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.11.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.11.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.11.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.11.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.11.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.11.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.11.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.12.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.12.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.12.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.12.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.12.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.12.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.12.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.12.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.13.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.13.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.13.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.13.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.13.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.13.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.13.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.13.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.14.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.14.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.14.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.14.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.14.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.14.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.14.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.14.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.15.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.15.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.15.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.15.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.15.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.15.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.15.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.15.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.16.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.16.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.16.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.16.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.16.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.16.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.16.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.16.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.17.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.17.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.17.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.17.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.17.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.17.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.17.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.17.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.18.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.18.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.18.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.18.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.18.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.18.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.18.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.18.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.19.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.19.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.19.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.19.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.19.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.19.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.19.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.19.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.20.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.20.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.20.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.20.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.20.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.20.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.20.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.20.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.21.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.21.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.21.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.21.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.21.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.21.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.21.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.21.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.22.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.22.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.22.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.22.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.22.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.22.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.22.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.22.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.23.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.23.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.23.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.23.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.23.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.23.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.23.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.23.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.24.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.24.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.24.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.24.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.24.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.24.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.24.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.24.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.25.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.25.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.25.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.25.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.25.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.25.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.25.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.25.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.26.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.26.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.26.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.26.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.26.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.26.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.26.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.26.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.27.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.27.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.27.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.27.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.27.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.27.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.27.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.27.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.28.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.28.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.28.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.28.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.28.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.28.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.28.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.28.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.29.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.29.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.29.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.29.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.29.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.29.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.29.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.29.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.30.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.30.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.30.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.30.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.30.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.30.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.30.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.30.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.31.attn.qkv.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.31.attn.qkv.lora_B.default.weight',
               torch.Size([3840, 64])),
              ('base_model.model.visual.blocks.31.attn.proj.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.31.attn.proj.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.visual.blocks.31.mlp.fc1.lora_A.default.weight',
               torch.Size([64, 1280])),
              ('base_model.model.visual.blocks.31.mlp.fc1.lora_B.default.weight',
               torch.Size([5120, 64])),
              ('base_model.model.visual.blocks.31.mlp.fc2.lora_A.default.weight',
               torch.Size([64, 5120])),
              ('base_model.model.visual.blocks.31.mlp.fc2.lora_B.default.weight',
               torch.Size([1280, 64])),
              ('base_model.model.model.embed_tokens.weight',
               torch.Size([151936, 1536])),
              ('base_model.model.model.layers.0.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.0.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.0.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.0.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.0.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.0.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.0.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.0.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.1.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.1.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.1.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.1.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.1.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.1.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.1.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.1.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.2.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.2.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.2.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.2.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.2.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.2.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.2.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.2.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.3.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.3.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.3.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.3.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.3.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.3.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.3.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.3.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.4.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.4.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.4.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.4.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.4.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.4.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.4.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.4.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.5.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.5.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.5.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.5.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.5.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.5.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.5.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.5.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.6.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.6.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.6.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.6.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.6.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.6.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.6.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.6.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.7.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.7.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.7.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.7.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.7.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.7.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.7.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.7.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.8.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.8.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.8.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.8.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.8.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.8.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.8.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.8.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.9.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.9.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.9.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.9.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.9.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.9.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.9.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.9.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.10.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.10.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.10.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.10.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.10.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.10.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.10.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.10.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.11.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.11.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.11.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.11.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.11.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.11.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.11.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.11.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.12.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.12.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.12.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.12.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.12.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.12.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.12.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.12.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.13.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.13.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.13.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.13.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.13.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.13.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.13.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.13.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.14.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.14.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.14.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.14.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.14.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.14.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.14.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.14.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.15.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.15.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.15.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.15.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.15.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.15.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.15.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.15.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.16.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.16.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.16.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.16.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.16.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.16.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.16.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.16.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.17.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.17.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.17.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.17.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.17.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.17.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.17.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.17.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.18.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.18.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.18.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.18.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.18.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.18.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.18.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.18.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.19.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.19.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.19.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.19.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.19.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.19.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.19.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.19.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.20.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.20.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.20.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.20.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.20.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.20.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.20.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.20.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.21.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.21.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.21.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.21.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.21.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.21.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.21.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.21.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.22.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.22.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.22.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.22.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.22.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.22.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.22.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.22.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.23.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.23.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.23.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.23.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.23.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.23.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.23.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.23.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.24.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.24.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.24.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.24.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.24.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.24.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.24.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.24.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.25.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.25.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.25.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.25.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.25.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.25.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.25.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.25.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.26.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.26.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.26.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.26.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.26.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.26.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.26.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.26.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.27.self_attn.q_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.27.self_attn.q_proj.lora_B.default.weight',
               torch.Size([1536, 64])),
              ('base_model.model.model.layers.27.self_attn.k_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.27.self_attn.k_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.27.self_attn.v_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.27.self_attn.v_proj.lora_B.default.weight',
               torch.Size([256, 64])),
              ('base_model.model.model.layers.27.self_attn.o_proj.lora_A.default.weight',
               torch.Size([64, 1536])),
              ('base_model.model.model.layers.27.self_attn.o_proj.lora_B.default.weight',
               torch.Size([1536, 64]))]),
 OrderedDict([('base_model.model.policy_head.pos_embed',
               torch.Size([1, 16, 1024])),
              ('base_model.model.policy_head.x_embedder.weight',
               torch.Size([1024, 10])),
              ('base_model.model.policy_head.t_embedder.mlp.0.weight',
               torch.Size([1024, 256])),
              ('base_model.model.policy_head.t_embedder.mlp.2.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.cond_obs_emb.weight',
               torch.Size([1024, 1543])),
              ('base_model.model.policy_head.blocks.0.attn.qkv.weight',
               torch.Size([3072, 1024])),
              ('base_model.model.policy_head.blocks.0.attn.proj.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.blocks.0.mlp.fc1.weight',
               torch.Size([4096, 1024])),
              ('base_model.model.policy_head.blocks.0.mlp.fc2.weight',
               torch.Size([1024, 4096])),
              ('base_model.model.policy_head.blocks.0.adaLN_modulation.1.weight',
               torch.Size([6144, 1024])),
              ('base_model.model.policy_head.blocks.1.attn.qkv.weight',
               torch.Size([3072, 1024])),
              ('base_model.model.policy_head.blocks.1.attn.proj.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.blocks.1.mlp.fc1.weight',
               torch.Size([4096, 1024])),
              ('base_model.model.policy_head.blocks.1.mlp.fc2.weight',
               torch.Size([1024, 4096])),
              ('base_model.model.policy_head.blocks.1.adaLN_modulation.1.weight',
               torch.Size([6144, 1024])),
              ('base_model.model.policy_head.blocks.2.attn.qkv.weight',
               torch.Size([3072, 1024])),
              ('base_model.model.policy_head.blocks.2.attn.proj.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.blocks.2.mlp.fc1.weight',
               torch.Size([4096, 1024])),
              ('base_model.model.policy_head.blocks.2.mlp.fc2.weight',
               torch.Size([1024, 4096])),
              ('base_model.model.policy_head.blocks.2.adaLN_modulation.1.weight',
               torch.Size([6144, 1024])),
              ('base_model.model.policy_head.blocks.3.attn.qkv.weight',
               torch.Size([3072, 1024])),
              ('base_model.model.policy_head.blocks.3.attn.proj.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.blocks.3.mlp.fc1.weight',
               torch.Size([4096, 1024])),
              ('base_model.model.policy_head.blocks.3.mlp.fc2.weight',
               torch.Size([1024, 4096])),
              ('base_model.model.policy_head.blocks.3.adaLN_modulation.1.weight',
               torch.Size([6144, 1024])),
              ('base_model.model.policy_head.blocks.4.attn.qkv.weight',
               torch.Size([3072, 1024])),
              ('base_model.model.policy_head.blocks.4.attn.proj.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.blocks.4.mlp.fc1.weight',
               torch.Size([4096, 1024])),
              ('base_model.model.policy_head.blocks.4.mlp.fc2.weight',
               torch.Size([1024, 4096])),
              ('base_model.model.policy_head.blocks.4.adaLN_modulation.1.weight',
               torch.Size([6144, 1024])),
              ('base_model.model.policy_head.blocks.5.attn.qkv.weight',
               torch.Size([3072, 1024])),
              ('base_model.model.policy_head.blocks.5.attn.proj.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.blocks.5.mlp.fc1.weight',
               torch.Size([4096, 1024])),
              ('base_model.model.policy_head.blocks.5.mlp.fc2.weight',
               torch.Size([1024, 4096])),
              ('base_model.model.policy_head.blocks.5.adaLN_modulation.1.weight',
               torch.Size([6144, 1024])),
              ('base_model.model.policy_head.blocks.6.attn.qkv.weight',
               torch.Size([3072, 1024])),
              ('base_model.model.policy_head.blocks.6.attn.proj.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.blocks.6.mlp.fc1.weight',
               torch.Size([4096, 1024])),
              ('base_model.model.policy_head.blocks.6.mlp.fc2.weight',
               torch.Size([1024, 4096])),
              ('base_model.model.policy_head.blocks.6.adaLN_modulation.1.weight',
               torch.Size([6144, 1024])),
              ('base_model.model.policy_head.blocks.7.attn.qkv.weight',
               torch.Size([3072, 1024])),
              ('base_model.model.policy_head.blocks.7.attn.proj.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.blocks.7.mlp.fc1.weight',
               torch.Size([4096, 1024])),
              ('base_model.model.policy_head.blocks.7.mlp.fc2.weight',
               torch.Size([1024, 4096])),
              ('base_model.model.policy_head.blocks.7.adaLN_modulation.1.weight',
               torch.Size([6144, 1024])),
              ('base_model.model.policy_head.blocks.8.attn.qkv.weight',
               torch.Size([3072, 1024])),
              ('base_model.model.policy_head.blocks.8.attn.proj.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.blocks.8.mlp.fc1.weight',
               torch.Size([4096, 1024])),
              ('base_model.model.policy_head.blocks.8.mlp.fc2.weight',
               torch.Size([1024, 4096])),
              ('base_model.model.policy_head.blocks.8.adaLN_modulation.1.weight',
               torch.Size([6144, 1024])),
              ('base_model.model.policy_head.blocks.9.attn.qkv.weight',
               torch.Size([3072, 1024])),
              ('base_model.model.policy_head.blocks.9.attn.proj.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.blocks.9.mlp.fc1.weight',
               torch.Size([4096, 1024])),
              ('base_model.model.policy_head.blocks.9.mlp.fc2.weight',
               torch.Size([1024, 4096])),
              ('base_model.model.policy_head.blocks.9.adaLN_modulation.1.weight',
               torch.Size([6144, 1024])),
              ('base_model.model.policy_head.blocks.10.attn.qkv.weight',
               torch.Size([3072, 1024])),
              ('base_model.model.policy_head.blocks.10.attn.proj.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.blocks.10.mlp.fc1.weight',
               torch.Size([4096, 1024])),
              ('base_model.model.policy_head.blocks.10.mlp.fc2.weight',
               torch.Size([1024, 4096])),
              ('base_model.model.policy_head.blocks.10.adaLN_modulation.1.weight',
               torch.Size([6144, 1024])),
              ('base_model.model.policy_head.blocks.11.attn.qkv.weight',
               torch.Size([3072, 1024])),
              ('base_model.model.policy_head.blocks.11.attn.proj.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.blocks.11.mlp.fc1.weight',
               torch.Size([4096, 1024])),
              ('base_model.model.policy_head.blocks.11.mlp.fc2.weight',
               torch.Size([1024, 4096])),
              ('base_model.model.policy_head.blocks.11.adaLN_modulation.1.weight',
               torch.Size([6144, 1024])),
              ('base_model.model.policy_head.blocks.12.attn.qkv.weight',
               torch.Size([3072, 1024])),
              ('base_model.model.policy_head.blocks.12.attn.proj.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.blocks.12.mlp.fc1.weight',
               torch.Size([4096, 1024])),
              ('base_model.model.policy_head.blocks.12.mlp.fc2.weight',
               torch.Size([1024, 4096])),
              ('base_model.model.policy_head.blocks.12.adaLN_modulation.1.weight',
               torch.Size([6144, 1024])),
              ('base_model.model.policy_head.blocks.13.attn.qkv.weight',
               torch.Size([3072, 1024])),
              ('base_model.model.policy_head.blocks.13.attn.proj.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.blocks.13.mlp.fc1.weight',
               torch.Size([4096, 1024])),
              ('base_model.model.policy_head.blocks.13.mlp.fc2.weight',
               torch.Size([1024, 4096])),
              ('base_model.model.policy_head.blocks.13.adaLN_modulation.1.weight',
               torch.Size([6144, 1024])),
              ('base_model.model.policy_head.blocks.14.attn.qkv.weight',
               torch.Size([3072, 1024])),
              ('base_model.model.policy_head.blocks.14.attn.proj.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.blocks.14.mlp.fc1.weight',
               torch.Size([4096, 1024])),
              ('base_model.model.policy_head.blocks.14.mlp.fc2.weight',
               torch.Size([1024, 4096])),
              ('base_model.model.policy_head.blocks.14.adaLN_modulation.1.weight',
               torch.Size([6144, 1024])),
              ('base_model.model.policy_head.blocks.15.attn.qkv.weight',
               torch.Size([3072, 1024])),
              ('base_model.model.policy_head.blocks.15.attn.proj.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.blocks.15.mlp.fc1.weight',
               torch.Size([4096, 1024])),
              ('base_model.model.policy_head.blocks.15.mlp.fc2.weight',
               torch.Size([1024, 4096])),
              ('base_model.model.policy_head.blocks.15.adaLN_modulation.1.weight',
               torch.Size([6144, 1024])),
              ('base_model.model.policy_head.blocks.16.attn.qkv.weight',
               torch.Size([3072, 1024])),
              ('base_model.model.policy_head.blocks.16.attn.proj.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.blocks.16.mlp.fc1.weight',
               torch.Size([4096, 1024])),
              ('base_model.model.policy_head.blocks.16.mlp.fc2.weight',
               torch.Size([1024, 4096])),
              ('base_model.model.policy_head.blocks.16.adaLN_modulation.1.weight',
               torch.Size([6144, 1024])),
              ('base_model.model.policy_head.blocks.17.attn.qkv.weight',
               torch.Size([3072, 1024])),
              ('base_model.model.policy_head.blocks.17.attn.proj.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.blocks.17.mlp.fc1.weight',
               torch.Size([4096, 1024])),
              ('base_model.model.policy_head.blocks.17.mlp.fc2.weight',
               torch.Size([1024, 4096])),
              ('base_model.model.policy_head.blocks.17.adaLN_modulation.1.weight',
               torch.Size([6144, 1024])),
              ('base_model.model.policy_head.blocks.18.attn.qkv.weight',
               torch.Size([3072, 1024])),
              ('base_model.model.policy_head.blocks.18.attn.proj.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.blocks.18.mlp.fc1.weight',
               torch.Size([4096, 1024])),
              ('base_model.model.policy_head.blocks.18.mlp.fc2.weight',
               torch.Size([1024, 4096])),
              ('base_model.model.policy_head.blocks.18.adaLN_modulation.1.weight',
               torch.Size([6144, 1024])),
              ('base_model.model.policy_head.blocks.19.attn.qkv.weight',
               torch.Size([3072, 1024])),
              ('base_model.model.policy_head.blocks.19.attn.proj.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.blocks.19.mlp.fc1.weight',
               torch.Size([4096, 1024])),
              ('base_model.model.policy_head.blocks.19.mlp.fc2.weight',
               torch.Size([1024, 4096])),
              ('base_model.model.policy_head.blocks.19.adaLN_modulation.1.weight',
               torch.Size([6144, 1024])),
              ('base_model.model.policy_head.blocks.20.attn.qkv.weight',
               torch.Size([3072, 1024])),
              ('base_model.model.policy_head.blocks.20.attn.proj.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.blocks.20.mlp.fc1.weight',
               torch.Size([4096, 1024])),
              ('base_model.model.policy_head.blocks.20.mlp.fc2.weight',
               torch.Size([1024, 4096])),
              ('base_model.model.policy_head.blocks.20.adaLN_modulation.1.weight',
               torch.Size([6144, 1024])),
              ('base_model.model.policy_head.blocks.21.attn.qkv.weight',
               torch.Size([3072, 1024])),
              ('base_model.model.policy_head.blocks.21.attn.proj.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.blocks.21.mlp.fc1.weight',
               torch.Size([4096, 1024])),
              ('base_model.model.policy_head.blocks.21.mlp.fc2.weight',
               torch.Size([1024, 4096])),
              ('base_model.model.policy_head.blocks.21.adaLN_modulation.1.weight',
               torch.Size([6144, 1024])),
              ('base_model.model.policy_head.blocks.22.attn.qkv.weight',
               torch.Size([3072, 1024])),
              ('base_model.model.policy_head.blocks.22.attn.proj.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.blocks.22.mlp.fc1.weight',
               torch.Size([4096, 1024])),
              ('base_model.model.policy_head.blocks.22.mlp.fc2.weight',
               torch.Size([1024, 4096])),
              ('base_model.model.policy_head.blocks.22.adaLN_modulation.1.weight',
               torch.Size([6144, 1024])),
              ('base_model.model.policy_head.blocks.23.attn.qkv.weight',
               torch.Size([3072, 1024])),
              ('base_model.model.policy_head.blocks.23.attn.proj.weight',
               torch.Size([1024, 1024])),
              ('base_model.model.policy_head.blocks.23.mlp.fc1.weight',
               torch.Size([4096, 1024])),
              ('base_model.model.policy_head.blocks.23.mlp.fc2.weight',
               torch.Size([1024, 4096])),
              ('base_model.model.policy_head.blocks.23.adaLN_modulation.1.weight',
               torch.Size([6144, 1024])),
              ('base_model.model.policy_head.final_layer.linear.weight',
               torch.Size([10, 1024])),
              ('base_model.model.policy_head.final_layer.adaLN_modulation.1.weight',
               torch.Size([2048, 1024])),
              ('base_model.model.input_action_proj.mlps.0.weight',
               torch.Size([1536, 1536])),
              ('base_model.model.input_action_proj.mlps.2.weight',
               torch.Size([1536, 1536])),
              ('base_model.model.reasoning_action_proj.mlps.0.weight',
               torch.Size([1536, 1536])),
              ('base_model.model.reasoning_action_proj.mlps.2.weight',
               torch.Size([1536, 1536]))]),
 OrderedDict([('base_model.model.policy_head.norm_after_pool.weight',
               torch.Size([1536])),
              ('base_model.model.policy_head.norm_after_pool.bias',
               torch.Size([1536])),
              ('base_model.model.policy_head.x_embedder.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.t_embedder.mlp.0.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.t_embedder.mlp.2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.cond_obs_emb.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.0.attn.qkv.bias',
               torch.Size([3072])),
              ('base_model.model.policy_head.blocks.0.attn.proj.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.0.mlp.fc1.bias',
               torch.Size([4096])),
              ('base_model.model.policy_head.blocks.0.mlp.fc2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.0.adaLN_modulation.1.bias',
               torch.Size([6144])),
              ('base_model.model.policy_head.blocks.1.attn.qkv.bias',
               torch.Size([3072])),
              ('base_model.model.policy_head.blocks.1.attn.proj.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.1.mlp.fc1.bias',
               torch.Size([4096])),
              ('base_model.model.policy_head.blocks.1.mlp.fc2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.1.adaLN_modulation.1.bias',
               torch.Size([6144])),
              ('base_model.model.policy_head.blocks.2.attn.qkv.bias',
               torch.Size([3072])),
              ('base_model.model.policy_head.blocks.2.attn.proj.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.2.mlp.fc1.bias',
               torch.Size([4096])),
              ('base_model.model.policy_head.blocks.2.mlp.fc2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.2.adaLN_modulation.1.bias',
               torch.Size([6144])),
              ('base_model.model.policy_head.blocks.3.attn.qkv.bias',
               torch.Size([3072])),
              ('base_model.model.policy_head.blocks.3.attn.proj.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.3.mlp.fc1.bias',
               torch.Size([4096])),
              ('base_model.model.policy_head.blocks.3.mlp.fc2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.3.adaLN_modulation.1.bias',
               torch.Size([6144])),
              ('base_model.model.policy_head.blocks.4.attn.qkv.bias',
               torch.Size([3072])),
              ('base_model.model.policy_head.blocks.4.attn.proj.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.4.mlp.fc1.bias',
               torch.Size([4096])),
              ('base_model.model.policy_head.blocks.4.mlp.fc2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.4.adaLN_modulation.1.bias',
               torch.Size([6144])),
              ('base_model.model.policy_head.blocks.5.attn.qkv.bias',
               torch.Size([3072])),
              ('base_model.model.policy_head.blocks.5.attn.proj.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.5.mlp.fc1.bias',
               torch.Size([4096])),
              ('base_model.model.policy_head.blocks.5.mlp.fc2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.5.adaLN_modulation.1.bias',
               torch.Size([6144])),
              ('base_model.model.policy_head.blocks.6.attn.qkv.bias',
               torch.Size([3072])),
              ('base_model.model.policy_head.blocks.6.attn.proj.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.6.mlp.fc1.bias',
               torch.Size([4096])),
              ('base_model.model.policy_head.blocks.6.mlp.fc2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.6.adaLN_modulation.1.bias',
               torch.Size([6144])),
              ('base_model.model.policy_head.blocks.7.attn.qkv.bias',
               torch.Size([3072])),
              ('base_model.model.policy_head.blocks.7.attn.proj.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.7.mlp.fc1.bias',
               torch.Size([4096])),
              ('base_model.model.policy_head.blocks.7.mlp.fc2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.7.adaLN_modulation.1.bias',
               torch.Size([6144])),
              ('base_model.model.policy_head.blocks.8.attn.qkv.bias',
               torch.Size([3072])),
              ('base_model.model.policy_head.blocks.8.attn.proj.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.8.mlp.fc1.bias',
               torch.Size([4096])),
              ('base_model.model.policy_head.blocks.8.mlp.fc2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.8.adaLN_modulation.1.bias',
               torch.Size([6144])),
              ('base_model.model.policy_head.blocks.9.attn.qkv.bias',
               torch.Size([3072])),
              ('base_model.model.policy_head.blocks.9.attn.proj.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.9.mlp.fc1.bias',
               torch.Size([4096])),
              ('base_model.model.policy_head.blocks.9.mlp.fc2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.9.adaLN_modulation.1.bias',
               torch.Size([6144])),
              ('base_model.model.policy_head.blocks.10.attn.qkv.bias',
               torch.Size([3072])),
              ('base_model.model.policy_head.blocks.10.attn.proj.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.10.mlp.fc1.bias',
               torch.Size([4096])),
              ('base_model.model.policy_head.blocks.10.mlp.fc2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.10.adaLN_modulation.1.bias',
               torch.Size([6144])),
              ('base_model.model.policy_head.blocks.11.attn.qkv.bias',
               torch.Size([3072])),
              ('base_model.model.policy_head.blocks.11.attn.proj.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.11.mlp.fc1.bias',
               torch.Size([4096])),
              ('base_model.model.policy_head.blocks.11.mlp.fc2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.11.adaLN_modulation.1.bias',
               torch.Size([6144])),
              ('base_model.model.policy_head.blocks.12.attn.qkv.bias',
               torch.Size([3072])),
              ('base_model.model.policy_head.blocks.12.attn.proj.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.12.mlp.fc1.bias',
               torch.Size([4096])),
              ('base_model.model.policy_head.blocks.12.mlp.fc2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.12.adaLN_modulation.1.bias',
               torch.Size([6144])),
              ('base_model.model.policy_head.blocks.13.attn.qkv.bias',
               torch.Size([3072])),
              ('base_model.model.policy_head.blocks.13.attn.proj.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.13.mlp.fc1.bias',
               torch.Size([4096])),
              ('base_model.model.policy_head.blocks.13.mlp.fc2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.13.adaLN_modulation.1.bias',
               torch.Size([6144])),
              ('base_model.model.policy_head.blocks.14.attn.qkv.bias',
               torch.Size([3072])),
              ('base_model.model.policy_head.blocks.14.attn.proj.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.14.mlp.fc1.bias',
               torch.Size([4096])),
              ('base_model.model.policy_head.blocks.14.mlp.fc2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.14.adaLN_modulation.1.bias',
               torch.Size([6144])),
              ('base_model.model.policy_head.blocks.15.attn.qkv.bias',
               torch.Size([3072])),
              ('base_model.model.policy_head.blocks.15.attn.proj.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.15.mlp.fc1.bias',
               torch.Size([4096])),
              ('base_model.model.policy_head.blocks.15.mlp.fc2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.15.adaLN_modulation.1.bias',
               torch.Size([6144])),
              ('base_model.model.policy_head.blocks.16.attn.qkv.bias',
               torch.Size([3072])),
              ('base_model.model.policy_head.blocks.16.attn.proj.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.16.mlp.fc1.bias',
               torch.Size([4096])),
              ('base_model.model.policy_head.blocks.16.mlp.fc2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.16.adaLN_modulation.1.bias',
               torch.Size([6144])),
              ('base_model.model.policy_head.blocks.17.attn.qkv.bias',
               torch.Size([3072])),
              ('base_model.model.policy_head.blocks.17.attn.proj.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.17.mlp.fc1.bias',
               torch.Size([4096])),
              ('base_model.model.policy_head.blocks.17.mlp.fc2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.17.adaLN_modulation.1.bias',
               torch.Size([6144])),
              ('base_model.model.policy_head.blocks.18.attn.qkv.bias',
               torch.Size([3072])),
              ('base_model.model.policy_head.blocks.18.attn.proj.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.18.mlp.fc1.bias',
               torch.Size([4096])),
              ('base_model.model.policy_head.blocks.18.mlp.fc2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.18.adaLN_modulation.1.bias',
               torch.Size([6144])),
              ('base_model.model.policy_head.blocks.19.attn.qkv.bias',
               torch.Size([3072])),
              ('base_model.model.policy_head.blocks.19.attn.proj.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.19.mlp.fc1.bias',
               torch.Size([4096])),
              ('base_model.model.policy_head.blocks.19.mlp.fc2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.19.adaLN_modulation.1.bias',
               torch.Size([6144])),
              ('base_model.model.policy_head.blocks.20.attn.qkv.bias',
               torch.Size([3072])),
              ('base_model.model.policy_head.blocks.20.attn.proj.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.20.mlp.fc1.bias',
               torch.Size([4096])),
              ('base_model.model.policy_head.blocks.20.mlp.fc2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.20.adaLN_modulation.1.bias',
               torch.Size([6144])),
              ('base_model.model.policy_head.blocks.21.attn.qkv.bias',
               torch.Size([3072])),
              ('base_model.model.policy_head.blocks.21.attn.proj.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.21.mlp.fc1.bias',
               torch.Size([4096])),
              ('base_model.model.policy_head.blocks.21.mlp.fc2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.21.adaLN_modulation.1.bias',
               torch.Size([6144])),
              ('base_model.model.policy_head.blocks.22.attn.qkv.bias',
               torch.Size([3072])),
              ('base_model.model.policy_head.blocks.22.attn.proj.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.22.mlp.fc1.bias',
               torch.Size([4096])),
              ('base_model.model.policy_head.blocks.22.mlp.fc2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.22.adaLN_modulation.1.bias',
               torch.Size([6144])),
              ('base_model.model.policy_head.blocks.23.attn.qkv.bias',
               torch.Size([3072])),
              ('base_model.model.policy_head.blocks.23.attn.proj.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.23.mlp.fc1.bias',
               torch.Size([4096])),
              ('base_model.model.policy_head.blocks.23.mlp.fc2.bias',
               torch.Size([1024])),
              ('base_model.model.policy_head.blocks.23.adaLN_modulation.1.bias',
               torch.Size([6144])),
              ('base_model.model.policy_head.final_layer.linear.bias',
               torch.Size([10])),
              ('base_model.model.policy_head.final_layer.adaLN_modulation.1.bias',
               torch.Size([2048])),
              ('base_model.model.input_action_proj.mlps.0.bias',
               torch.Size([1536])),
              ('base_model.model.input_action_proj.mlps.2.bias',
               torch.Size([1536])),
              ('base_model.model.reasoning_action_proj.mlps.0.bias',
               torch.Size([1536])),
              ('base_model.model.reasoning_action_proj.mlps.2.bias',
               torch.Size([1536]))])]
"""
